model:
  vocab_size: 32000
  dim: 128
  num_layers: 2
  heads: 4
  titan_level:
    name: titan
    update_period: 8
  cms_levels:
    - name: cms_fast
      update_period: 1
    - name: cms_mid
      update_period: 4
    - name: cms_slow
      update_period: 16

data:
  vocab_size: 32000
  seq_len: 64
  dataset_size: 2048
  batch_size: 8

train:
  steps: 10
  log_interval: 1

optim:
  lr: 3.0e-4
